### ISSUE TITLE
When importing PowerBIEmbed in jest tests, fails right away with Cannot read property 'getRandomValues' of undefined

### ISSUE THREAD

**Issue by jimmy3912msncom** [microsoft/powerbi-client-react#21]
Versions:
"powerbi-client": "2.14.1"
"powerbi-client-react": "1.2.0"

So I have a react component that imports PowerBIEmbed as below.

``
import { PowerBIEmbed } from 'powerbi-client-react';
``

It works completely fine but when I try to reference the component with the PowerBIEmbed import it fails right away with the below: 

TypeError: Cannot read property 'getRandomValues' of undefined

at Function.WindowPostMessageProxy.createRandomString (../../common/temp/node_modules/.pnpm/powerbi-client@2.14.1/node_modules/powerbi-client/dist/webpack:/~/window-post-message-proxy/dist/windowPostMessageProxy.js:125:1)
      at new WindowPostMessageProxy (../../common/temp/node_modules/.pnpm/powerbi-client@2.14.1/node_modules/powerbi-client/dist/webpack:/~/window-post-message-proxy/dist/windowPostMessageProxy.js:77:1)
      at exports.wpmpFactory (../../common/temp/node_modules/.pnpm/powerbi-client@2.14.1/node_modules/powerbi-client/dist/webpack:/src/factories.ts:24:10)
      at new Service (../../common/temp/node_modules/.pnpm/powerbi-client@2.14.1/node_modules/powerbi-client/dist/webpack:/src/service.ts:140:17)
      at Object.<anonymous> (../../common/temp/node_modules/.pnpm/powerbi-client@2.14.1/node_modules/powerbi-client/dist/webpack:/src/powerbi-client.ts:58:15)
      at __webpack_require__ (../../common/temp/node_modules/.pnpm/powerbi-client@2.14.1/node_modules/powerbi-client/dist/webpack:/webpack/bootstrap e3359f5a2f7f804bc3cd:19:1)
      at ../../common/temp/node_modules/.pnpm/powerbi-client@2.14.1/node_modules/powerbi-client/dist/webpack:/webpack/bootstrap e3359f5a2f7f804bc3cd:39:1
      at ../../common/temp/node_modules/.pnpm/powerbi-client@2.14.1/node_modules/powerbi-client/dist/powerbi.js:54:10
      at webpackUniversalModuleDefinition (../../common/temp/node_modules/.pnpm/powerbi-client@2.14.1/node_modules/powerbi-client/dist/webpack:/webpack/universalModuleDefinition:3:1)
      at Object.<anonymous> (../../common/temp/node_modules/.pnpm/powerbi-client@2.14.1/node_modules/powerbi-client/dist/webpack:/webpack/universalModuleDefinition:10:2)
      at ../../common/temp/node_modules/.pnpm/powerbi-client-react@1.2.0_react@16.12.0/node_modules/powerbi-client-react/dist/webpack:/powerbi-client-react/webpack/universalModuleDefinition:3:28
      at Object.<anonymous> (../../common/temp/node_modules/.pnpm/powerbi-client-react@1.2.0_react@16.12.0/node_modules/powerbi-client-react/dist/webpack:/powerbi-client-react/webpack/universalModuleDefinition:1:1)

**Comment by anant-k-singh** [comment]
_powerbi-client-react_ requires the `getRandomValues` from `window.crypto` object.
The reason for this error is that JSDOM does not implement the `window.crypto`.
As a fix, you can setup your jest to use some polyfill package before running tests. Eg: `@trust/webcrypto`

**Comment by allemas** [comment]
Adding this in setupTests.js worked for me 

```const crypto = require('crypto');

Object.defineProperty(window.self, 'crypto', {
  value: {
    getRandomValues: (arr) => crypto.randomBytes(arr.length)
  }
});
```

> If some code uses a method which JSDOM (the DOM implementation used by Jest) hasn't implemented yet, testing it is not easily possible. [Documentation here](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom)

**Comment by vathul** [comment]
I tried this (typescript):
 
 import crypto from 'crypto';

Object.defineProperty(window.self, 'crypto', {
  value: {
    getRandomValues: (arr: string | never[]) => crypto.randomBytes(arr.length)
  }
});

But this continues to throw the same error.
