### ISSUE TITLE
Error handling response: TypeError: Cannot set property 'blocked' of undefined

### ISSUE THREAD

**Issue by alexbruneauab** [microsoft/powerbi-client-react#37]
I downloaded the demo and ran it.

When I look at the console I receive an Error handling response after the rendering of the report.

Here is a copy of the console log:

Embedded object of type "report" received
[WDS] Live Reloading enabled.
Embedded object of type "report" received
Report has loaded
Report has rendered
reportEmbed?uid=5hdp6:1 Error handling response: TypeError: Cannot set property 'blocked' of undefined
    at Object.preventFormFilling (chrome-extension://cpaibbcbodhimfnjnakiidgbpiehfgci/scripts/content-script.js:10:13632)
    at Object.initFillForms (chrome-extension://cpaibbcbodhimfnjnakiidgbpiehfgci/scripts/content-script.js:10:14865)
    at Object.secondBackgroundResponse (chrome-extension://cpaibbcbodhimfnjnakiidgbpiehfgci/scripts/content-script.js:11:1995)
    at chrome-extension://cpaibbcbodhimfnjnakiidgbpiehfgci/scripts/content-script.js:8:11437
    at chrome-extension://cpaibbcbodhimfnjnakiidgbpiehfgci/scripts/content-script.js:8:10668

**Comment by KotanaSai21** [comment]
Demo has been updated. If the issue still persists, raise a new issue.
