### ISSUE TITLE
AI: StringValueTooLong message:"string value is too long. It has been truncated to 1024 characters."

### ISSUE THREAD

**Issue by lucasramosdev** [microsoft/powerbi-client-react#66]
Hi, I've been using powerbi-client-react for 4 months and today I got this error:

```
AI: StringValueTooLong message:"string value is too long. It has been truncated to 1024 characters." props:"{value:Error: Uncaught (in promise): Object: {\activityId\:\1c1614fb-8fe6-422f-aba6-6e1f2ebc250f\,\requestId\:\b3c3ab7e-c4ae-4e72-b835-116f68d2ca46\,\status\:401,\error\:{\message\:\conceptualSchema Exception: Unexpected end of JSON input\,\code\:\FrontLoadException\}}\n    at O (https://content.powerapps.com/resource/powerbiwfe/scripts/reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5:24109)\n    at O (https://content.powerapps.com/resource/powerbiwfe/scripts/reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5:23642)\n    at https://content.powerapps.com/resource/powerbiwfe/scripts/reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5:24932\n    at t.invokeTask (https://content.powerapps.com/resource/powerbiwfe/scripts/reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5:15128)\n    at Object.onInvokeTask (https://content.powerapps.com/resource/powerbiwfe/scripts/reportEmbed.vendors.min.1bed30b38d667f001425.js:1:494927)\n    at t.invokeTask (https://content.powerapps.com/resource/powerbiwfe/scr}"
o.warnToConsole @ ai.0.js:1
o.throwInternal @ ai.0.js:1
t.sanitizeString @ ai.0.js:1
t.sanitizeProperties @ ai.0.js:1
n @ ai.0.js:1
n.trackEvent @ ai.0.js:1
ce.trackEventInternal @ reportEmbed.min.a0f43d91253440acb4e4.js:1
ce.endTimedEvent @ reportEmbed.min.a0f43d91253440acb4e4.js:1
ce.logEvent @ reportEmbed.min.a0f43d91253440acb4e4.js:1
ce.logEvent @ reportEmbed.min.a0f43d91253440acb4e4.js:1
M.logEventInternal @ reportEmbed.min.a0f43d91253440acb4e4.js:1
M.logEvent @ reportEmbed.min.a0f43d91253440acb4e4.js:1
i.handleErrorAndLogTelemetry @ powerbiportal.dependencies.bundle.min.55bec80780e00c8e79e8.js:19
d.handleError @ reportEmbed.min.a0f43d91253440acb4e4.js:1
i.handleError @ reportEmbed.min.a0f43d91253440acb4e4.js:1
next @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
F.__tryOrUnsub @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
F.next @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
F._next @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
F.next @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
L.next @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
n.emit @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
t.invoke @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
e.run @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
t.runOutsideAngular @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
onHandleError @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
t.handleError @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
e.runGuarded @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
t @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
Zone.__load_patch.n.microtaskDrainDone @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
m @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
Promise.then (assíncrono)
y @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
t.scheduleTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
onScheduleTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
t.scheduleTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
e.scheduleTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
e.scheduleMicroTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
x @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
O @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
(anônimo) @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
Promise.then (assíncrono)
(anônimo) @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
t @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
D.t.then @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
d.prefetchConceptualSchema @ reportEmbed.min.a0f43d91253440acb4e4.js:1
(anônimo) @ reportEmbed.min.a0f43d91253440acb4e4.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
c @ powerbiportal.dependencies.bundle.min.55bec80780e00c8e79e8.js:11
g @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
d.startReportEmbed @ reportEmbed.min.a0f43d91253440acb4e4.js:1
(anônimo) @ reportEmbed.min.a0f43d91253440acb4e4.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
c @ powerbiportal.dependencies.bundle.min.55bec80780e00c8e79e8.js:11
g @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
d.initializeReportEmbed @ reportEmbed.min.a0f43d91253440acb4e4.js:1
(anônimo) @ reportEmbed.min.a0f43d91253440acb4e4.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
fe @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
c.processQueue @ powerbiportal.dependencies.bundle.min.55bec80780e00c8e79e8.js:11
(anônimo) @ powerbiportal.dependencies.bundle.min.55bec80780e00c8e79e8.js:11
$digest @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:159
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
t.invoke @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
onInvoke @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
t.invoke @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
e.run @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
t.run @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
F.__tryOrUnsub @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
F.next @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
F._next @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
F.next @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
L.next @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
n.emit @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
Hd @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
onHasTask @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
t.hasTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
t._updateTaskCount @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
e._updateTaskCount @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
e.runTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
m @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
Promise.then (assíncrono)
y @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
t.scheduleTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
onScheduleTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
t.scheduleTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
e.scheduleTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
e.scheduleMicroTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
x @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
O @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
(anônimo) @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
Promise.then (assíncrono)
(anônimo) @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
t @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
D.t.then @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
(anônimo) @ reportEmbed.min.a0f43d91253440acb4e4.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
c @ powerbiportal.dependencies.bundle.min.55bec80780e00c8e79e8.js:11
g @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
d.getClusterUrl @ reportEmbed.min.a0f43d91253440acb4e4.js:1
(anônimo) @ reportEmbed.min.a0f43d91253440acb4e4.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
c @ powerbiportal.dependencies.bundle.min.55bec80780e00c8e79e8.js:11
g @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
d.initClusterUri @ reportEmbed.min.a0f43d91253440acb4e4.js:1
(anônimo) @ reportEmbed.min.a0f43d91253440acb4e4.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
c @ powerbiportal.dependencies.bundle.min.55bec80780e00c8e79e8.js:11
g @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
d.loadReportForSaasPaasEmbed @ reportEmbed.min.a0f43d91253440acb4e4.js:1
(anônimo) @ reportEmbed.min.a0f43d91253440acb4e4.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
fe @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
c.processQueue @ powerbiportal.dependencies.bundle.min.55bec80780e00c8e79e8.js:11
(anônimo) @ powerbiportal.dependencies.bundle.min.55bec80780e00c8e79e8.js:11
$digest @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:159
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
t.invoke @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
onInvoke @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
t.invoke @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
e.run @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
t.run @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
(anônimo) @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
F.__tryOrUnsub @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
F.next @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
F._next @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
F.next @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
L.next @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
n.emit @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
Hd @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
onHasTask @ reportEmbed.vendors.min.1bed30b38d667f001425.js:1
t.hasTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
t._updateTaskCount @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
e._updateTaskCount @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
e.runTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
m @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
e.invokeTask @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
g @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5
y @ reportembed.externals.bundle.min.202d9027481f1b4f2087.js:5

```
No changes have been made, does anyone have an idea how to fix it?

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. This is an old issue, is it still relevant?

**Comment by v-MadhavC** [comment]
We are waiting for your response. If no response is received within the next couple of weeks, the issue will be closed.

**Comment by ayeshurun** [comment]
The issue is closed since no response was received.
